import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Plus, Loader2 } from 'lucide-react';
import { useActiveRegions } from '@/hooks/useRegions';
import { useCreateShipment, useCustomers } from '@/hooks/useShipments';
import { useAuth } from '@/hooks/useAuth';

const formSchema = z.object({
  customer_id: z.string().min(1, 'Please select a customer'),
  origin_region: z.string().min(1, 'Please select a region'),
  total_weight_kg: z.coerce.number().positive('Weight must be positive'),
  description: z.string().optional(),
  warehouse_location: z.string().optional(),
});

type FormValues = z.infer<typeof formSchema>;

export function CreateShipmentDialog() {
  const [open, setOpen] = useState(false);
  const { user } = useAuth();
  const createShipment = useCreateShipment();
  const { data: customers, isLoading: customersLoading } = useCustomers();
  const { data: regions, isLoading: regionsLoading } = useActiveRegions();

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      description: '',
      warehouse_location: '',
    },
  });

  const onSubmit = async (values: FormValues) => {
    await createShipment.mutateAsync({
      customer_id: values.customer_id,
      origin_region: values.origin_region as any,
      total_weight_kg: values.total_weight_kg,
      description: values.description || null,
      warehouse_location: values.warehouse_location || null,
      created_by: user?.id,
      tracking_number: '', // Will be generated by DB function
    });
    setOpen(false);
    form.reset();
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="bg-brand-gold hover:bg-brand-gold/90 text-brand-navy font-semibold">
          <Plus className="h-4 w-4 mr-2" />
          New Shipment
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="text-xl font-bold">Create New Shipment</DialogTitle>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="customer_id"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Customer</FormLabel>
                  <Select onValueChange={field.onChange} value={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select a customer" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {customersLoading ? (
                        <div className="p-2 text-center text-muted-foreground">Loading...</div>
                      ) : customers?.length === 0 ? (
                        <div className="p-2 text-center text-muted-foreground">No customers found</div>
                      ) : (
                        customers?.map((customer) => (
                          <SelectItem key={customer.id} value={customer.id}>
                            {customer.name} {customer.company_name && `(${customer.company_name})`}
                          </SelectItem>
                        ))
                      )}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="origin_region"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Origin Region</FormLabel>
                  <Select onValueChange={field.onChange} value={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select origin region" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {regionsLoading ? (
                        <div className="p-2 text-center text-muted-foreground">Loading...</div>
                      ) : (
                        regions?.map((region) => (
                          <SelectItem key={region.id} value={region.code}>
                            {region.flag_emoji} {region.name}
                          </SelectItem>
                        ))
                      )}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="total_weight_kg"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Total Weight (kg)</FormLabel>
                  <FormControl>
                    <Input type="number" step="0.01" placeholder="0.00" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Description</FormLabel>
                  <FormControl>
                    <Textarea 
                      placeholder="Describe the shipment contents..."
                      className="resize-none"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="warehouse_location"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Warehouse Location</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g., Rack A-12" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="flex justify-end gap-3 pt-4">
              <Button type="button" variant="outline" onClick={() => setOpen(false)}>
                Cancel
              </Button>
              <Button 
                type="submit" 
                disabled={createShipment.isPending}
                className="bg-brand-gold hover:bg-brand-gold/90 text-brand-navy"
              >
                {createShipment.isPending && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
                Create Shipment
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
