import { useState, useEffect } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  FormDescription,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { Loader2, Package, DollarSign, Weight, MapPin, User, CheckCircle } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { useCustomers, useCreateShipment } from '@/hooks/useShipments';
import { useRegionPricingByRegion, calculateShipmentCost } from '@/hooks/useRegionPricing';
import { REGIONS, CURRENCY_SYMBOLS } from '@/lib/constants';
import { useNavigate } from 'react-router-dom';
import { cn } from '@/lib/utils';

const formSchema = z.object({
  customer_id: z.string().min(1, 'Please select a customer'),
  total_weight_kg: z.coerce.number().positive('Weight must be greater than 0'),
  description: z.string().max(500, 'Description must be under 500 characters').optional(),
  warehouse_location: z.string().max(100, 'Location must be under 100 characters').optional(),
});

type FormValues = z.infer<typeof formSchema>;

export function ShipmentUploadForm() {
  const { user, getRegion } = useAuth();
  const navigate = useNavigate();
  const region = getRegion();
  const regionInfo = region ? REGIONS[region] : null;
  
  const { data: customers, isLoading: customersLoading } = useCustomers();
  const { data: pricing, isLoading: pricingLoading } = useRegionPricingByRegion(region);
  const createShipment = useCreateShipment();

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      customer_id: '',
      total_weight_kg: 0,
      description: '',
      warehouse_location: '',
    },
  });

  const watchedWeight = useWatch({ control: form.control, name: 'total_weight_kg' });
  const cost = calculateShipmentCost(watchedWeight || 0, pricing);
  const currencySymbol = CURRENCY_SYMBOLS[cost.currency] || cost.currency;

  const onSubmit = async (values: FormValues) => {
    if (!region) return;

    await createShipment.mutateAsync({
      customer_id: values.customer_id,
      origin_region: region,
      total_weight_kg: values.total_weight_kg,
      description: values.description || null,
      warehouse_location: values.warehouse_location || null,
      created_by: user?.id,
      agent_id: user?.id,
      tracking_number: '', // Generated by DB
    });

    navigate('/agent/shipments');
  };

  if (!region) {
    return (
      <Card className="max-w-xl mx-auto">
        <CardContent className="py-12 text-center">
          <MapPin className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <h3 className="text-lg font-semibold mb-2">Region Not Assigned</h3>
          <p className="text-muted-foreground">
            You don't have a region assigned to your account. Please contact an administrator.
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="max-w-4xl mx-auto">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Form */}
        <div className="lg:col-span-2">
          <Card className="shadow-lg border-0">
            <CardHeader className="pb-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center">
                  <Package className="w-6 h-6 text-primary" />
                </div>
                <div>
                  <CardTitle className="font-heading text-xl">New Shipment</CardTitle>
                  <CardDescription>
                    Upload a shipment from {regionInfo?.flag} {regionInfo?.label}
                  </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                  {/* Customer Selection */}
                  <FormField
                    control={form.control}
                    name="customer_id"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="flex items-center gap-2">
                          <User className="w-4 h-4" />
                          Customer
                        </FormLabel>
                        <Select onValueChange={field.onChange} value={field.value}>
                          <FormControl>
                            <SelectTrigger className="h-12">
                              <SelectValue placeholder="Select a customer" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            {customersLoading ? (
                              <div className="p-4 text-center">
                                <Loader2 className="w-4 h-4 animate-spin mx-auto" />
                              </div>
                            ) : customers?.length === 0 ? (
                              <div className="p-4 text-center text-muted-foreground">
                                No customers found
                              </div>
                            ) : (
                              customers?.map((customer) => (
                                <SelectItem key={customer.id} value={customer.id}>
                                  <div className="flex items-center gap-2">
                                    <span className="font-medium">{customer.name}</span>
                                    {customer.company_name && (
                                      <span className="text-muted-foreground">
                                        ({customer.company_name})
                                      </span>
                                    )}
                                  </div>
                                </SelectItem>
                              ))
                            )}
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* Weight Input */}
                  <FormField
                    control={form.control}
                    name="total_weight_kg"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="flex items-center gap-2">
                          <Weight className="w-4 h-4" />
                          Total Weight (kg)
                        </FormLabel>
                        <FormControl>
                          <div className="relative">
                            <Input
                              type="number"
                              step="0.01"
                              min="0"
                              placeholder="0.00"
                              className="h-12 text-lg pr-12"
                              {...field}
                            />
                            <span className="absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground font-medium">
                              kg
                            </span>
                          </div>
                        </FormControl>
                        <FormDescription>
                          Rate: {currencySymbol}{pricing?.customer_rate_per_kg || 0}/kg
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* Description */}
                  <FormField
                    control={form.control}
                    name="description"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Description (Optional)</FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder="Describe the shipment contents..."
                            className="min-h-[100px] resize-none"
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* Warehouse Location */}
                  <FormField
                    control={form.control}
                    name="warehouse_location"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="flex items-center gap-2">
                          <MapPin className="w-4 h-4" />
                          Warehouse Location (Optional)
                        </FormLabel>
                        <FormControl>
                          <Input
                            placeholder="e.g., Rack A-12, Bay 3"
                            className="h-12"
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <Separator />

                  {/* Submit Button */}
                  <Button
                    type="submit"
                    size="lg"
                    className="w-full h-14 text-lg font-semibold"
                    disabled={createShipment.isPending || pricingLoading}
                  >
                    {createShipment.isPending ? (
                      <>
                        <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                        Creating Shipment...
                      </>
                    ) : (
                      <>
                        <CheckCircle className="w-5 h-5 mr-2" />
                        Create Shipment
                      </>
                    )}
                  </Button>
                </form>
              </Form>
            </CardContent>
          </Card>
        </div>

        {/* Cost Summary Sidebar */}
        <div className="lg:col-span-1">
          <Card className="shadow-lg border-0 sticky top-24">
            <CardHeader className="pb-4">
              <CardTitle className="font-heading text-lg flex items-center gap-2">
                <DollarSign className="w-5 h-5 text-primary" />
                Cost Summary
              </CardTitle>
              <CardDescription>Automatic calculation based on weight</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Region Badge */}
              <div className="flex items-center justify-between p-3 rounded-lg bg-muted/50">
                <span className="text-sm text-muted-foreground">Origin Region</span>
                <Badge variant="outline" className="gap-1.5">
                  {regionInfo?.flag} {regionInfo?.label}
                </Badge>
              </div>

              {/* Weight Display */}
              <div className="flex items-center justify-between p-3 rounded-lg bg-muted/50">
                <span className="text-sm text-muted-foreground">Weight</span>
                <span className="font-semibold">{watchedWeight || 0} kg</span>
              </div>

              <Separator />

              {/* Cost Breakdown */}
              <div className="space-y-3">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">
                    Subtotal ({watchedWeight || 0} kg × {currencySymbol}{pricing?.customer_rate_per_kg || 0})
                  </span>
                  <span className="font-medium">{currencySymbol}{cost.subtotal.toFixed(2)}</span>
                </div>
                
                {cost.handlingFee > 0 && (
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">Handling Fee</span>
                    <span className="font-medium">{currencySymbol}{cost.handlingFee.toFixed(2)}</span>
                  </div>
                )}

                <Separator />

                <div className="flex items-center justify-between">
                  <span className="font-semibold">Total</span>
                  <span className={cn(
                    "text-2xl font-bold",
                    cost.total > 0 ? "text-primary" : "text-muted-foreground"
                  )}>
                    {currencySymbol}{cost.total.toFixed(2)}
                  </span>
                </div>
              </div>

              {/* Info Note */}
              <div className="mt-4 p-3 rounded-lg bg-primary/5 border border-primary/10">
                <p className="text-xs text-muted-foreground">
                  This is an estimated cost. Final invoice may vary based on actual measurements and additional services.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
